<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP1HkzKv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP1HkzKv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP1HkzKv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP1HkzKv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP1HkzKv\App_KernelDevDebugContainer([
    'container.build_hash' => 'P1HkzKv',
    'container.build_id' => '4ea42868',
    'container.build_time' => 1596192484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP1HkzKv');
