<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFatP84k\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFatP84k/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFatP84k.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFatP84k\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFatP84k\App_KernelTestDebugContainer([
    'container.build_hash' => 'FatP84k',
    'container.build_id' => 'a3cfc5fe',
    'container.build_time' => 1596207234,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFatP84k');
